name: CI

on:
  push:
    branches:
      - featureV2

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm ci

      - name: Executar lint
        run: npm run lint

      - name: Executar build
        run: npm run build